apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: squid-ui CI/CD

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Run mode: full or deploy_only"
        required: false
        type: string
        default: "full"
      enable_smart_tests:
        description: "Enable CloudBees Smart Tests"
        required: false
        type: string
        default: "true"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  test:
    if: ${{ inputs.run_mode != 'deploy_only' }}
    uses: stacksphereio/core-workflows/.cloudbees/workflows/component-test.yaml@main
    with:
      component_name: squid-ui
      language: node
      coverage_root: src
      debug: "false"
      enable_smart_tests: ${{ inputs.enable_smart_tests || 'true' }}
    secrets: inherit
    vars: inherit

  build:
    if: ${{ inputs.run_mode != 'deploy_only' }}
    needs: [test]
    uses: stacksphereio/core-workflows/.cloudbees/workflows/component-build.yaml@main
    with:
      component_name: squid-ui
      docker_user: ${{ vars.DOCKER_USER }}
      commit_sha: ${{ cloudbees.scm.sha }}
      push_latest: "true"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy-component:
    if: ${{ cloudbees.scm.branch == 'main' || inputs.run_mode == 'deploy_only' }}
    needs: [build]
    environment: integ
    uses: stacksphereio/core-workflows/.cloudbees/workflows/component-deploy.yaml@main
    with:
      component_name: squid-ui
      version: ${{ needs.build.outputs.VERSION }}
      environment: integ
      stack_name: squid
      org_name: stacksphereio
      docker_repo: ${{ vars.DOCKER_USER }}/squid-ui
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      commit_sha: ${{ cloudbees.scm.sha }}
      uses_postgres: false
      uses_liquibase: false
      hostname: squid.integ.stacksphereio.se-main-demo.sa-demo.beescloud.com
      feature_flags_enabled: true
      feature_flags_secret_name: feature-mgmt
      feature_flags_secret_key: FM_KEY
      feature_flags_create_secret: true
      replica_count: "1"
      image_pull_policy: Always
    secrets: inherit
    vars: inherit
